name: Deploy to Firebase Hosting Manual Action
on:
  workflow_dispatch:
    inputs:
      enviroment:
        type: choice
        description: 'Enviroment'
        required: true
        options:
          - stg
          - prd
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build-${{ github.event.inputs.enviroment }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: "${{ github.event.inputs.enviroment != 'prd' }}"
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: wallbee-app
          target: ${{ github.event.inputs.enviroment }}-wallbee
      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: "${{ github.event.inputs.enviroment == 'prd' }}"
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: wallbee-app
          target: wallbee
